# Generated by Django 4.0.3 on 2022-07-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
