# Generated by Django 4.0.3 on 2022-07-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_name_contact_last_name_contact_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
