# Generated by Django 4.0.3 on 2022-07-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='role',
            new_name='adm',
        ),
        migrations.AddField(
            model_name='contact',
            name='reg',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
