# Generated by Django 4.0.3 on 2022-07-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_rename_role_contact_adm_contact_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='adm',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='reg',
        ),
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('0', 'Admin'), ('1', 'Regular')], max_length=10, null=True),
        ),
    ]
