# Generated by Django 4.0.3 on 2022-07-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_contact_adm_remove_contact_reg_contact_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('0', 'Admin'), ('1', 'Regular')], max_length=10),
        ),
    ]
